steps:
  # Step 1: Ambil secret dari Secret Manager dan buat file .env
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=vite-env > .env

  # Step 2: Install dependencies
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]

  # Step 3: Build the Vite app (akan membaca .env yang sudah dibuat)
  - name: "node:20"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 4: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --quiet",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY