# cloudbuild.yaml
steps:
  # Step 1: Install dependencies
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Build the Vite app
  - name: "node:20"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 3: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --quiet",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY